version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - catalog-api
      - basket-api
      - discount-api
      - ordering-api

  catalog-api:
    build: ./catalog-api
    ports:
      - "4001:4001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/catalog
    depends_on:
      - mongo

  basket-api:
    build: ./basket-api
    ports:
      - "4002:4002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  discount-api:
    build: ./discount-api
    ports:
      - "4003:4003"
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=discounts
    depends_on:
      - postgres

  ordering-api:
    build: ./ordering-api
    ports:
      - "4004:4004"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=orders
    depends_on:
      - mysql
      - rabbitmq

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: discounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI
