version: "3.9"

services:
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - catalog-api
  #     - basket-api
  #     - discount-api
  #     - ordering-api

  basket-api:
    build: ./basket-api
    ports:
      - "4002:4002"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  discount-api:
    build: .
    ports:
      - "4000:4000"
      - "50051:50051"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discountdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  ordering-api:
    build: ./ordering-api
    ports:
      - "4004:4004"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Oyugi222f
      - MYSQL_DB=ordersdb
      - RABBIT_HOST=rabbitmq
    depends_on:
      - mysql
      - rabbitmq

  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discountdb
    ports:
      - "5432:5432"
    volumes:
      - discount_data:/var/lib/postgresql/data
      - ./discount-api/db/init:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Oyugi222f
      MYSQL_DATABASE: ordersdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI

volumes:
  mysql_data:
